import React from 'react';

const Footer: React.FC = () => {
    return (
        <footer className="max-w-md pb-16 text-sm text-slate-500 sm:pb-0">
            <p>
                Inspired by the portfolio of Brittany Chiang and crafted with React and Tailwind CSS. Coded in Visual Studio Code. All text is generated by Gemini. Deployed with Vercel.
            </p>
        </footer>
    )
}

export default Footer;